In [71]:
import pandas as pd
import numpy as np
import datetime as dt

In [173]:
pf1 = pd.read_excel('C:/Users/omesh/Desktop/CAPSTONE/Estimize.xlsx')

In [5]:

pf2 = pd.read_excel('C:/Users/omesh/Downloads/moreEstimizeReleases.xlsx')

In [184]:
pf1.head()

,Fiscal Year,Fiscal Quarter,ACT EPS,WS EPS Est,ESZ EPS Est,Release Date,ID,symbol,fiscalDate,Actual EPS vs WS,...,Per1d,Per2d,Per3d,Per5d,shortName,refSectorShort,mktCap,Earnings Surprise %,Month,Day
1,2018.0,1.0,3.89,3.843,3.844296,2018-02-01,131754,AAPL,2018 Q1,Beat,...,-4.339015,-6.729050,-2.831088,-7.527715,SPX 100,E Technology,Mega Cap,1.188886,February,1.0
3,2018.0,2.0,2.73,2.670,2.724264,2018-05-01,133987,AAPL,2018 Q2,Beat,...,4.417504,4.606742,8.710822,10.023655,SPX 100,E Technology,Mega Cap,0.210568,May,1.0
5,2018.0,3.0,2.34,2.173,2.217906,2018-07-31,136224,AAPL,2018 Q3,Beat,...,5.891008,8.986284,9.301592,8.839140,SPX 100,E Technology,Mega Cap,5.504926,July,31.0
7,2018.0,4.0,2.91,2.788,2.842092,2018-11-01,146839,AAPL,2018 Q4,Beat,...,-6.633066,-9.283593,-8.302583,-6.178562,SPX 100,E Technology,Mega Cap,2.389383,November,1.0
9,2019.0,1.0,4.18,4.170,4.183036,2019-01-29,149518,AAPL,2019 Q1,Beat,...,6.833463,7.602793,7.654513,12.606672,SPX 100,E Technology,Mega Cap,-0.072571,January,29.0

In [175]:
earning_spz = ((pf1['ACT EPS'] - pf1['ESZ EPS Est']) / abs(pf1['ESZ EPS Est'])) * 100

In [178]:
earning_spz.shape

(2158, 1)

In [177]:
earning_spz = pd.Series(earning_spz, name = 'Earnings Surprise %').to_frame()

In [179]:
pf1 = pd.concat([pf1, earning_spz], axis = 1, join = 'outer')

In [7]:
pf2.head()

,Fiscal Year,Fiscal Quarter,ACT EPS,ACT Revenue,ESZ EPS Est UW,ESZ REV Est UW,WS REV Est,WS EPS Est,ESZ REV Est,ESZ EPS Est,...,markNextRelease,eszWsEpsDelta,TimeNow,releaseDate1m,resultStatus,nextEszWSDelta,ESZ Delta,ESZ Delta %,coverage,EPS Estimate Delta
0,2018,1,0.47,7626.000,0.461169,7465.368421,7445.333,0.457,7465.502381,0.464911,...,NaN,0.007911,2020-03-10 12:55:02.314,2020-04-10 12:55:02.314,NaN,NaN,0.005089,0.010945,NaN,0.007911
1,2018,1,0.56,589.222,0.375937,573.230882,573.407,0.363,579.136216,0.385542,...,NaN,0.022542,2020-03-10 12:55:02.314,2020-04-10 12:55:02.314,NaN,NaN,0.174458,0.452499,NaN,0.022542
2,2018,1,0.58,6073.700,0.578889,6152.876344,6136.674,0.566,6130.364847,0.575762,...,NaN,0.009762,2020-03-10 12:55:02.314,2020-04-10 12:55:02.314,NaN,NaN,0.004238,0.007361,NaN,0.009762
3,2018,1,0.61,12136.000,0.615106,12206.704278,12140.105,0.601,12178.975025,0.612601,...,NaN,0.011601,2020-03-10 12:55:02.314,2020-04-10 12:55:02.314,NaN,NaN,-0.002601,-0.004246,NaN,0.011601
4,2018,1,0.62,22791.000,0.600645,22717.711864,22732.691,0.588,22741.586280,0.608167,...,NaN,0.020167,2020-03-10 12:55:02.314,2020-04-10 12:55:02.314,NaN,NaN,0.011833,0.019458,NaN,0.020167

In [180]:
pf1 = pf1.drop(pf1[pf1.shortName == 'setup'].index)

In [80]:
pf1['Release Date'] = pd.to_datetime(pf1['Release Date'])

In [181]:
pf1.shape

(2150, 24)

In [182]:
pf1['Month'] = pf1['Release Date'].dt.month_name()

In [183]:
pf1['Day'] = pf1['Release Date'].dt.day

In [22]:
pf1 = pf1.drop(pf1[pf1.ID == '4f066ccec6efa653ac00ec8c'].index)

In [185]:
pf1 = pf1[pf1['Earnings Surprise %'].notnull()]

In [200]:
pf1.dtypes

Fiscal Year                   float64
Fiscal Quarter                float64
ACT EPS                       float64
WS EPS Est                    float64
ESZ EPS Est                   float64
Release Date           datetime64[ns]
ID                             object
symbol                         object
fiscalDate                     object
Actual EPS vs WS               object
WS EPS Dif                    float64
WS EPS % Dif                  float64
Actual EPS vs ESZ              object
ESZ EPS Dif                   float64
ESZ EPS % Dif                 float64
close                         float64
Per1d                         float64
Per2d                         float64
Per3d                         float64
Per5d                         float64
shortName                      object
refSectorShort                 object
mktCap                         object
Earnings Surprise %           float64
Month                          object
Day                           float64
dtype: object

In [39]:
pf0.dtypes

ACT EPS                float64
ESZ EPS Est            float64
ID                       int32
symbol                  object
fiscalDate              object
Actual EPS vs ESZ       object
ESZ EPS Dif            float64
ESZ EPS % Dif          float64
close                  float64
Per1d                  float64
Per2d                  float64
Per3d                  float64
Per5d                  float64
shortName               object
refSectorShort          object
mktCap                  object
Earnings Surprise %    float64
Release Date            object
dtype: object

In [27]:
pf1['ID'] = pf1['ID'].astype(int)

In [28]:
pf0 = pd.merge(pf1, pf2[["ID","Release Date"]], on="ID", how="left")

In [29]:
pf0.head()

,ACT EPS,ESZ EPS Est,ID,symbol,fiscalDate,Actual EPS vs ESZ,ESZ EPS Dif,ESZ EPS % Dif,close,Per1d,Per2d,Per3d,Per5d,shortName,refSectorShort,mktCap,Earnings Surprise %,Release Date
0,3.89,3.844296,131754,AAPL,2018 Q1,Beat,0.045704,0.011749,167.78,-4.339015,-6.729050,-2.831088,-7.527715,SPX 100,E Technology,Mega Cap,1.188886,2018-02-01T16:00:00-05:00
1,2.73,2.724264,133987,AAPL,2018 Q2,Beat,0.005736,0.002101,169.10,4.417504,4.606742,8.710822,10.023655,SPX 100,E Technology,Mega Cap,0.210568,2018-05-01T16:00:00-04:00
2,2.34,2.217906,136224,AAPL,2018 Q3,Beat,0.122094,0.052177,190.29,5.891008,8.986284,9.301592,8.839140,SPX 100,E Technology,Mega Cap,5.504926,2018-07-31T16:00:00-04:00
3,2.91,2.842092,146839,AAPL,2018 Q4,Beat,0.067908,0.023336,222.22,-6.633066,-9.283593,-8.302583,-6.178562,SPX 100,E Technology,Mega Cap,2.389383,2018-11-01T16:00:00-04:00
4,4.18,4.183036,149518,AAPL,2019 Q1,Miss,0.003036,0.000726,154.68,6.833463,7.602793,7.654513,12.606672,SPX 100,E Technology,Mega Cap,-0.072571,2019-01-29T16:00:00-05:00

In [37]:
pf0['Release Date'] = pd.to_datetime(pf0['Release Date'])

In [47]:
pf0['local_rdate'] = pd.to_datetime(pf0['Release Date'] , cache = True, utc = True)

In [59]:
pf0.head()

,ACT EPS,ESZ EPS Est,ID,symbol,fiscalDate,Actual EPS vs ESZ,ESZ EPS Dif,ESZ EPS % Dif,close,Per1d,...,shortName,refSectorShort,mktCap,Earnings Surprise %,Release Date,local_rdate,Month,Day,year,quarter
0,3.89,3.844296,131754,AAPL,2018 Q1,Beat,0.045704,0.011749,167.78,-4.339015,...,SPX 100,E Technology,Mega Cap,1.188886,2018-02-01 16:00:00-05:00,2018-02-01 21:00:00+00:00,February,1.0,2018,Q1
1,2.73,2.724264,133987,AAPL,2018 Q2,Beat,0.005736,0.002101,169.10,4.417504,...,SPX 100,E Technology,Mega Cap,0.210568,2018-05-01 16:00:00-04:00,2018-05-01 20:00:00+00:00,May,1.0,2018,Q2
2,2.34,2.217906,136224,AAPL,2018 Q3,Beat,0.122094,0.052177,190.29,5.891008,...,SPX 100,E Technology,Mega Cap,5.504926,2018-07-31 16:00:00-04:00,2018-07-31 20:00:00+00:00,July,31.0,2018,Q3
3,2.91,2.842092,146839,AAPL,2018 Q4,Beat,0.067908,0.023336,222.22,-6.633066,...,SPX 100,E Technology,Mega Cap,2.389383,2018-11-01 16:00:00-04:00,2018-11-01 20:00:00+00:00,November,1.0,2018,Q4
4,4.18,4.183036,149518,AAPL,2019 Q1,Miss,0.003036,0.000726,154.68,6.833463,...,SPX 100,E Technology,Mega Cap,-0.072571,2019-01-29 16:00:00-05:00,2019-01-29 21:00:00+00:00,January,29.0,2019,Q1

In [55]:
pf0['Month'] = pf0['local_rdate'].dt.month_name()

In [53]:
pf0['Day'] = pf0['local_rdate'].dt.day

In [92]:
pf1.to_csv('Pf_Est.csv', index = False, encoding='utf-8-sig')

In [91]:
pf1[['year','quarter']] = pf1['fiscalDate'].str.split(' ',expand=True)

C:\Users\omesh\Anaconda3\lib\site-packages\pandas\core\frame.py:3494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [187]:
sectors = ['Com Services', 'Comms','Con Services', 'Durables','E Technology','Energy Min','Finance','Health','Health Tech','Industrials','Non-Durables','Non-Energy Minerals','Producers','Retail','Tech Services','Transports','Utilities']

In [188]:
fiscal_qtr = ['2018 Q1','2018 Q2','2018 Q3','2018 Q4','2019 Q1','2019 Q2','2019 Q3','2019 Q4','2020 Q1','2020 Q2','2020 Q3']

In [189]:
EPS_vs_ESZ = ['Beat','Miss']

In [190]:
def subset(sector,fis,pf1,B_M):
    i = sector
    j = fis
    df = pf1[(pf1['refSectorShort'] == i) & (pf1['fiscalDate'] == j) & (pf1['Actual EPS vs ESZ'] == B_M) ]
    return df

In [191]:
data ={}
for i in sectors:
    for j in fiscal_qtr:
        for k in EPS_vs_ESZ:
            data[i+j+k] = subset(i,j,pf1,k)

In [192]:
new_df = pd.DataFrame(columns=['name','min1','min2','no. of records','Sector Trend'])

for name,df in data.items():
    df = df.sort_values(by = ['Release Date'])
    r,c = np.shape(df)
    d = []
    if r!=1:
        d.append({'name': name, 'min1': df.iloc[0:r//2, 23].min(), 'min2': df.iloc[r//2:, 23].min(),'no. of records': r})
    else:
        d.append({'name': name, 'min1': df.iloc[0, 23].min(), 'no. of records': r})
    #print(r)
    m = pd.DataFrame(d)
    new_df = new_df.append(m)
    #new_df['name'] = name
    #new_df['min1'] = df.iloc[0:r//2, :].
    #new_df['min2'] = df.iloc[r//2:,:]

In [193]:
new_df.head(374)

   Sector Trend       min1        min2                     name no. of records
0           NaN   8.028477  146.899861  Com Services2018 Q1Beat              2
0           NaN        NaN         NaN  Com Services2018 Q1Miss              0
0           NaN  24.548356         NaN  Com Services2018 Q2Beat              1
0           NaN  -1.890960         NaN  Com Services2018 Q2Miss              1
0           NaN  20.354507         NaN  Com Services2018 Q3Beat              1
..          ...        ...         ...                      ...            ...
0           NaN        NaN         NaN     Utilities2020 Q1Miss              0
0           NaN        NaN         NaN     Utilities2020 Q2Beat              0
0           NaN        NaN         NaN     Utilities2020 Q2Miss              0
0           NaN        NaN         NaN     Utilities2020 Q3Beat              0
0           NaN        NaN         NaN     Utilities2020 Q3Miss              0

[374 rows x 5 columns]

In [110]:
df_temp = data['Com Services2018 Q1Beat']

In [117]:
new_df = pd.DataFrame()
new_df = new_df.append(df_temp)

In [118]:
new_df

,Fiscal Year,Fiscal Quarter,ACT EPS,WS EPS Est,ESZ EPS Est,Release Date,ID,symbol,fiscalDate,Actual EPS vs WS,...,Per3d,Per5d,shortName,refSectorShort,mktCap,Earnings Surprise %,Month,Day,year,quarter
525,2018.0,1.0,0.82,0.740,0.759059,2018-05-08,135320,KAR,2018 Q1,Beat,...,0.260368,-1.580807,Gilead,Com Services,Mid Cap,8.028477,May,8.0,2018,Q1
1051,2018.0,1.0,0.34,0.098,0.137708,2018-05-10,137808,TTD,2018 Q1,Beat,...,52.133510,52.550730,Gilead,Com Services,Large Cap,146.899861,May,10.0,2018,Q1

In [114]:
df_temp.sort_values(by = ['Release Date'])

,Fiscal Year,Fiscal Quarter,ACT EPS,WS EPS Est,ESZ EPS Est,Release Date,ID,symbol,fiscalDate,Actual EPS vs WS,...,Per3d,Per5d,shortName,refSectorShort,mktCap,Earnings Surprise %,Month,Day,year,quarter
525,2018.0,1.0,0.82,0.740,0.759059,2018-05-08,135320,KAR,2018 Q1,Beat,...,0.260368,-1.580807,Gilead,Com Services,Mid Cap,8.028477,May,8.0,2018,Q1
1051,2018.0,1.0,0.34,0.098,0.137708,2018-05-10,137808,TTD,2018 Q1,Beat,...,52.133510,52.550730,Gilead,Com Services,Large Cap,146.899861,May,10.0,2018,Q1

In [196]:
new_df.to_csv('Sector-trend_pf.csv', index = False, encoding='utf-8-sig')

In [152]:
pd.concat([new_df,pd.DataFrame(columns='Sector_trend')])

TypeError: Index(...) must be called with a collection of some kind, 'Sector_trend' was passed

In [204]:
dfn

,Fiscal Year,Fiscal Quarter,ACT EPS,WS EPS Est,ESZ EPS Est,Release Date,ID,symbol,fiscalDate,Actual EPS vs WS,...,Per1d,Per2d,Per3d,Per5d,shortName,refSectorShort,mktCap,Earnings Surprise %,Month,Day
525,2018.0,1.0,0.82,0.740,0.759059,2018-05-08,135320,KAR,2018 Q1,Beat,...,-1.134462,-0.223173,0.260368,-1.580807,Gilead,Com Services,Mid Cap,8.028477,May,8.0
1051,2018.0,1.0,0.34,0.098,0.137708,2018-05-10,137808,TTD,2018 Q1,Beat,...,43.390859,42.082306,52.133510,52.550730,Gilead,Com Services,Large Cap,146.899861,May,10.0

In [194]:

for i in range(np.shape(new_df)[0]):
    min1,min2 = new_df[['min1','min2']].iloc[i]
    print(min1,min2)
    if new_df['no. of records'].iloc[i]>1:
        if abs(min1)<abs(min2):
            new_df.iloc[i,0] = 'Yes'
        else:
            new_df.iloc[i,0] = 'No'
    else:
        new_df.iloc[i,0] = 'Insufficient Data'

8.028476886409642 146.89986058611302
nan nan
24.548355696953283 nan
-1.8909597307098778 nan
20.354506942573007 nan
-4.091383447033788 nan
31.053246824984765 nan
-0.017071299117137086 nan
45.14254827008149 nan
-12.627434070447766 nan
28.514581354205546 nan
-28.72661198255418 nan
nan nan
-8.1403672000358 -5.128172941031319
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
5.646958203807274 nan
-3.497170895496055 -255.90079903313728
3.365340226995481 4.2527632589557305
-250.07754881242016 nan
0.6317653910703529 7.300327642308899
-4.65002937998528 nan
1.5097739541717874 0.07702586589228673
-203.97554958032353 nan
0.632934161875363 20.1787803098382
-0.1949076277666031 nan
0.8560269561471314 nan
-2.3242900880528023 -1813.6698618213743
0.5522735065492874 nan
-0.4184968116987561 -121.36775421510058
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
0.7360606835338815 1.9457598764348045
-0.9873842942744588 nan
1.3355568732909722 1.1096871625819533
-1.093339305606313 nan
5.28250775340605 2.069856215143554
-6.6171261659553515 -3.356421504697628
1.5469081103323385 0.8514922357229562
-6.491091320293374 -18.095947451040505
5.2361293885345255 12.58791963400738
-16.00774273207283 -5.706071814864534
0.22475983357058082 0.26052087085698505
-3.4847234474381366 -22.696721891939358
5.252987161064283 1.4700713657778746
-24.982347131311595 -5.469978948131639
4.707506960864996 4.5133279139300315
-3.8639795508502814 nan
6.629120164877539 nan
nan nan
8.638441876512784 nan
nan nan
nan nan
nan nan
2.3632327311032806 8.619698313511206
nan nan
nan nan
-5.976028121361851 -28.52571587671572
40.005972157254504 nan
-7.472795911749183 nan
9.822726454957717 nan
-7.894284862610933 nan
58.30275143489922 22.400216066961313
nan nan
8.874142951607867 nan
-1.0943915048702197 nan
21.39947921802648 36.55104401518173
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
1.1888861731913183 2.582578836590701
-0.42461023250997065 -86.95928487689635
0.21056797354162257 0.7082064396414443
-2.744303533540342 -3.0266654040842305
5.504926414774209 1.4851541195580085
-13.778954959566938 -33.63692532946193
1.0963492865462259 0.06648000370366623
-18.1342473998928 -10.13851301046219
0.6013241145568629 4.256539523761432
-0.07257081783220949 -3.8412024515896657
0.48402951309720244 0.5640352904695568
-9.01778043153952 -11.535678291677726
0.5934345860191852 1.3191391560991594
-0.9365855569007837 -34.09604157434896
3.1351407250896113 2.9712578920898394
-0.1211150410078585 -0.158326657913204
53.92986061806193 1.7803318312710452
-25.76610031744357 -4.219640230951485
46.993586412431284 nan
-22.165732163977463 nan
nan nan
-7.6669590173316635 nan
26.730269283074716 29.566478588911316
-7.543250072235839 nan
1.8297729522981527 nan
-15.203212758043952 -26.77950412303017
11.849627183210908 16.600854762829105
nan nan
5.851141056523336 3.2523858327964428
-0.5588267891656366 nan
4.364411388847632 3.6290839736268254
-1.882942393113582 -40.08014967764859
6.2029164309901015 nan
-8.5673487286773 -0.8496791730035924
1.3624939821380684 nan
-1.8397188544015948 -76.19422435715522
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
2.4087738565353844 4.552056730433936
-1.4535719248629766 -0.016312271487338024
0.9588209282793914 0.6186572297328309
-14.093591223715812 -3.116991003469764
2.092011337147236 1.0100708433605727
-0.3093105767608741 -49.20347467904656
1.5945826268814955 1.1883438412926588
-12.479461604347525 -101.95581345850968
1.868795759046795 2.3402673328376338
-5.262945641282673 -38.933920085452364
0.7534333274086201 0.04666238521829405
-4.629303971830056 -91.3931209951621
0.32235958728021924 2.831260241737979
-12.471041510367739 -64.89955623357892
0.9986258673740762 nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
2.44824272644243 nan
nan nan
1.6165032300128637 nan
nan nan
1.514243301413799 nan
nan nan
0.2692338641135514 nan
nan nan
2.8262094473742754 nan
nan nan
2.0763943924941346 nan
nan nan
2.686217433679462 nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
1.4408945810739606 1.6578682045482882
-13.992952630851999 -104.3699404074518
0.5439150998379981 0.1164182974780698
-26.590498161744392 -101.77778067752377
0.09726008710584844 1.3388060434999107
-58.10757138947227 -322.87983458255763
1.7408641146109558 0.7124288201135208
-3.568206564752157 -430.4544459532235
0.6501566203461966 0.3052170121862886
-13.763147763292944 -49.08403990972366
0.3935315933449603 0.763743815990536
-14.153569695933054 -170.61038755442652
0.4085461017313729 0.7997996383597133
-2.247566917145277 -28.851688418892746
3.592063615272847 nan
nan nan
4.092675289860981 nan
nan nan
nan nan
-0.20431800807622016 nan
nan nan
nan nan
nan nan
-0.6374353953647701 -5.701292542252152
1.7861578906540383 1.5360512648078273
-4.207247193410548 nan
0.9791917933044991 nan
-1.9085608671739398 -2.000286925274414
1.8891280820276704 nan
-0.10939212316575303 -4.588599026562868
1.0860910269660586 nan
-4.172102674263163 -4.970018625774119
nan nan
-6.48192615761079 -4.8029105687109475
6.039988761639098 1.247993772056625
-2.4795291602863196 nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
1.0945494934112139 0.7267172079301139
-0.5761048284647485 -7.976858598783291
1.970389774454321 0.08295013343008917
-1.263490019656472 -91.1583056778045
0.07833276162754121 0.012126797610200558
-1.5525813512025037 -69.91528915373273
2.17628607304146 1.0660370912026158
-1.5117168117768955 -30.546648340785087
0.4457920682792307 1.541160728669277
-3.566586051726012 -6.742801600260117
2.060703521989726 0.060137562518096585
-2.7414274027480716 -11.040646387566857
1.9820485918438442 0.9455571240993154
-0.20916357641046426 -2.9631175335251383
1.9264661795368847 nan
-11.249034810532102 nan
19.20454152617283 8.97970457234265
nan nan
13.702900602583165 nan
nan nan
nan nan
nan nan
0.6213739226732745 83.4943448377921
nan nan
1.645565103312131 nan
-11.499297454669168 nan
1.3209725071859075 5.171163908292542
nan nan
2.321918552258654 14.648474195627454
nan nan
19.065975702487936 nan
-4.94973699098802 nan
1.325319477549573 nan
-6.499591628426677 nan
nan nan
-4.119773104430838 -2.905649819588779
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
1.8795891408603969 2.7807919494143096
-0.2647104984737391 -1.229448319437308
2.6249359231390783 2.5582845313182374
-0.49047804143533513 -4.279981846554
0.18673470325124272 1.4224204965429499
-8.294264087786601 -5.2868092908050395
0.24724604490382676 1.1566115766201066
-15.140426332356116 -1.7885096059568242
3.6676488891442127 3.283159055726486
-11.671375568013804 -13.664658080678699
0.14536794647101425 5.677878774319574
-10.935505286787588 -30.027530250836023
2.340380094925273 1.9892795407059103
-2.2269299512250873 -6.6359170706051005
0.44246941392236605 nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
2.722940103774629 3.899497832946647
-9.405426320957645 -5.2909321578971875
0.13495173017176756 2.407508860117893
-3.7416534090746496 -6.41800404317177
0.12677837071834436 6.538964245138577
-11.274192156029956 -3.4825901841176963
0.6678907569835871 1.9879548247680703
-3.716046230246956 -3.152867187395223
0.25045425596555493 1.8363808033111082
-2.411695651063864 -9.158061478662116
1.200532061069618 1.4977877128815311
-5.3241601682281985 -13.279570143231531
0.7459994678675936 1.2693771602780826
-12.094738520421956 -6.339242812594708
4.477663239187816 5.049371864626921
-1.5452969860411179 nan
6.824650053853702 nan
-1.6025617252997597 nan
2.3309276938344925 nan
nan nan
3.73131727613543 nan
nan nan
0.8417982598592402 2.916546842179288
-19.10515823533926 -12.316392842586007
0.568629721682701 1.4280388783636087
-100.0 -522.4927597402673
1.246399815075935 0.16817268502471563
-17.934347501013153 -30.79220899446915
0.20730038968255543 1.804091120207696
-957.0520155032824 -64.87951655768296
0.6569767234587344 0.6569767234587344
-40.17991350615135 -6726.502783594325
0.260694035791049 0.5288798801411788
-59.87663769248012 -37.167753009939666
0.46848869484275607 0.45129582392754086
-100.0 -280.12856348551634
2.9396380106909064 0.4980083354275844
-8.346068325831393 -31.08871701770927
7.641816787191607 2.3837098323513115
-6.0744281316783395 -21.769201671303314
5.632571334290328 13.036944619922538
-100.0 -83.57288418390927
4.32839162418425 18.283544426761598
-526.07744169388 -29.508467519663267
3.977282561081588 0.6939666158073833
-0.5110814789351404 nan
9.575167602270023 0.39849207948756377
-1.4697026616387985 nan
18.332470156377678 1.379373262003567
-1.0132894512689192 -11.579611748379286
1.645256834440146 0.8443220877133553
-15.814329992268789 nan
14.651854060127508 nan
-10.322900610043396 -4.6041271026921065
3.5084101661248686 0.594620180818221
-1.2575852684238575 nan
0.04732345030942049 7.969537316246522
-4.534395515310327 -4.220522791418942
3.215662382989068 nan
nan nan
nan nan
-5.53235034372063 nan
nan nan
-12.078133695684446 nan
nan nan
nan nan
2.7288475372124217 9.124625045690953
nan nan
1.026687171532434 10.795927628169997
-11.358585555552185 nan
0.5744695100441031 2.7622486101157318
-3.349142990690012 -453.0196168163703
nan nan
-7.327412434852334 -135.05766668385172
9.257090798120945 nan
-6.1331688646568425 -427.8947547550928
1.9124733338282105 7.3505242787262945
-10.487221188226705 -197.265692239248
6.326237467849646 4.586699067614394
-565.7337289390531 nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan

In [195]:
new_df.head(40)

,Sector Trend,min1,min2,name,no. of records
0,Yes,8.028477,146.899861,Com Services2018 Q1Beat,2
0,Insufficient Data,NaN,NaN,Com Services2018 Q1Miss,0
0,Insufficient Data,24.548356,NaN,Com Services2018 Q2Beat,1
0,Insufficient Data,-1.890960,NaN,Com Services2018 Q2Miss,1
0,Insufficient Data,20.354507,NaN,Com Services2018 Q3Beat,1
0,Insufficient Data,-4.091383,NaN,Com Services2018 Q3Miss,1
0,Insufficient Data,31.053247,NaN,Com Services2018 Q4Beat,1
0,Insufficient Data,-0.017071,NaN,Com Services2018 Q4Miss,1
0,Insufficient Data,45.142548,NaN,Com Services2019 Q1Beat,1
0,Insufficient Data,-12.627434,NaN,Com Services2019 Q1Miss,1
0,Insufficient Data,28.514581,NaN,Com Services2019 Q2Beat,1
0,Insufficient Data,-28.726612,NaN,Com Services2019 Q2Miss,1
0,Insufficient Data,NaN,NaN,Com Services2019 Q3Beat,0
0,No,-8.140367,-5.128173,Com Services2019 Q3Miss,2
0,Insufficient Data,NaN,NaN,Com Services2019 Q4Beat,0
0,Insufficient Data,NaN,NaN,Com Services2019 Q4Miss,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q1Beat,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q1Miss,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q2Beat,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q2Miss,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q3Beat,0
0,Insufficient Data,NaN,NaN,Com Services2020 Q3Miss,0
0,Insufficient Data,5.646958,NaN,Comms2018 Q1Beat,1
0,Yes,-3.497171,-255.900799,Comms2018 Q1Miss,2
0,Yes,3.365340,4.252763,Comms2018 Q2Beat,2
0,Insufficient Data,-250.077549,NaN,Comms2018 Q2Miss,1
0,Yes,0.631765,7.300328,Comms2018 Q3Beat,2
0,Insufficient Data,-4.650029,NaN,Comms2018 Q3Miss,1
0,No,1.509774,0.077026,Comms2018 Q4Beat,2
0,Insufficient Data,-203.975550,NaN,Comms2018 Q4Miss,1
0,Yes,0.632934,20.178780,Comms2019 Q1Beat,2
0,Insufficient Data,-0.194908,NaN,Comms2019 Q1Miss,1
0,Insufficient Data,0.856027,NaN,Comms2019 Q2Beat,1
0,Yes,-2.324290,-1813.669862,Comms2019 Q2Miss,2
0,Insufficient Data,0.552274,NaN,Comms2019 Q3Beat,1
0,Yes,-0.418497,-121.367754,Comms2019 Q3Miss,2
0,Insufficient Data,NaN,NaN,Comms2019 Q4Beat,0
0,Insufficient Data,NaN,NaN,Comms2019 Q4Miss,0
0,Insufficient Data,NaN,NaN,Comms2020 Q1Beat,0
0,Insufficient Data,NaN,NaN,Comms2020 Q1Miss,0

In [202]:
def subset(sector,fis,pf1):
    i = sector
    j = fis
    dfn = pf1[(pf1['refSectorShort'] == i) & (pf1['fiscalDate'] == j)]
    return dfn

In [203]:
data_n ={}
for i in sectors:
    for j in fiscal_qtr:
        data[i+j] = subset(i,j,pf1)

In [199]:
n_df = pd.DataFrame(columns=['name','b1','b2','m1','m2','no. of records','Sector Trend'])

for name,dfn in data.items():
    dfn = dfn.sort_values(by = ['Release Date'])
    r,c = np.shape(dfn)
    d1 = []
    if r!=1:
        d1.append({'name': name, 'b1': dfn.iloc[0:r//2, 9].value_counts()['Beat'], 'b2': dfn.iloc[r//2:, 9].value_counts()['Beat'],'m1': dfn.iloc[0:r//2, 9].value_counts()['Miss'],'m2': dfn.iloc[r//2:, 9].value_counts()['Miss'],'no. of records': r})
    else:
        d1.append({'name': name, 'b1': dfn.iloc[0, 9].value_counts()['Beat'], 'm1': dfn.iloc[0, 9].value_counts()['Miss'],'no. of records': r})
    #print(r)
    n = pd.DataFrame(d1)
    n_df = n_df.append(n)
    #new_df['name'] = name
    #new_df['min1'] = df.iloc[0:r//2, :].
    #new_df['min2'] = df.iloc[r//2:,:]

KeyError: 'Beat'